name: GitHub Action demo

on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '15 6 ? * SUN'

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Branch {github.ref}"
      - run: echo "Event {github.event}"
      - run: echo "Repository {github.repository}"; tree
