name: Hello World Docker CI

on:
  push:
    paths: hello-world-docker-action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Hello Action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@joaqapr'
          
      - run: echo "Output ${{ steps.hello-action.outputs.time }}"
